name: Eleme
url: "http://eleme.io"
timezone: Asia/Shanghai

markdown: redcarpet

redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - autolink
    - tables

pygments: true
permalink: /blog/:year/:title/
paginate: 50
paginate_path: "blog/page/:num/"
exclude:
  - README.md
  - Makefile

nav:
  - title: 博客
    link: /blog/
  - title: 关于
    link: /about/
