name: Eleme
url: "http://eleme.io"
timezone: Asia/Shanghai

markdown: redcarpet

redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - autolink
    - tables
    - strikethrough

permalink: /blog/:year/:title/
paginate: 1000
paginate_path: "blog/page/:num/"
exclude:
  - README.md
  - Makefile
  - fabfile.py

disqus: eleme
ga: "UA-2513347-13"
nav:
  - title: 博客
    link: /blog/
  - title: 关于
    link: /about/
